library("MASS", lib.loc="C:/Program Files/R/R-3.5.1/library")


remove.packages("Mass")
install.packages("MASS")
library("MASS", lib.loc="~/R/win-library/3.5")
library("MASS", lib.loc="C:/Program Files/R/R-3.5.1/library")

library("datasets", lib.loc="C:/Program Files/R/R-3.5.1/library")
library("graphics", lib.loc="C:/Program Files/R/R-3.5.1/library")
library("methods", lib.loc="C:/Program Files/R/R-3.5.1/library")
library("grDevices", lib.loc="C:/Program Files/R/R-3.5.1/library")

library("MASS", lib.loc="~/R/win-library/3.5")
library("datasets", lib.loc="C:/Program Files/R/R-3.5.1/library")
library("graphics", lib.loc="C:/Program Files/R/R-3.5.1/library")
library("grDevices", lib.loc="C:/Program Files/R/R-3.5.1/library")
library("MASS", lib.loc="C:/Program Files/R/R-3.5.1/library")
library("methods", lib.loc="C:/Program Files/R/R-3.5.1/library")
fit<-lm(Log_Price~.,data=Data)
summary(fit)
fit<-lm(Log_Price~House.style.numbered,data=Data)
summary(fit)
fit<-lm(Log_Price~Central.Air.numbered,data=Data)
summary(fit)
fit<-lm(Log_Price~Bedroom_AbvGr,data=Data)
summary(fit)
fit<-lm(Log_Price~Fireplaces,data=Data)
summary(fit)
fit<-lm(Log_Price~Lot_Area,data=Data)
summary(fit)
fit<-lm(Log_Price~Gr_Liv_Area,data=Data)
summary(fit)
fit<-lm(Log_Price~Garage_Area,data=Data)
summary(fit)
fit<-lm(Log_Price~Basement_Area,data=Data)
summary(fit)
fit<-lm(Log_Price~Total_Bathroom,data=Data)
summary(fit)
fit<-lm(Log_Price~Overall_Qual,data=Data)
summary(fit)
fit<-lm(Log_Price~House.style.numbered+Central.Air.numbered+Bedroom_AbvGr+Fireplaces+Lot_Area+Gr_Liv_Area+Basement_Area+Total_Bathroom+Overall_Qual,data=Data)
summary(fit)
fit<-lm(Log_Price~Central.Air.numbered+Bedroom_AbvGr+Fireplaces+Lot_Area+Gr_Liv_Area+Basement_Area+Total_Bathroom+Overall_Qual,data=Data)
summary(fit)
library("MASS", lib.loc="~/R/win-library/3.5")
library("datasets", lib.loc="C:/Program Files/R/R-3.5.1/library")
library("graphics", lib.loc="C:/Program Files/R/R-3.5.1/library")
library("grDevices", lib.loc="C:/Program Files/R/R-3.5.1/library")
library("MASS", lib.loc="C:/Program Files/R/R-3.5.1/library")
library("methods", lib.loc="C:/Program Files/R/R-3.5.1/library")
fit<-lm(Log_Price~House.style.numbered,data=Data)
summary(fit)
fit<-lm(Log_Price~Central.Air.numbered,data=Data)
summary(fit)
fit<-lm(Log_Price~Bedroom_AbvGr,data=Data)
summary(fit)
fit<-lm(Log_Price~Fireplaces,data=Data)
summary(fit)
fit<-lm(Log_Price~Gr_Liv_Area,data=Data)
summary(fit)
fit<-lm(Log_Price~Garage_Area,data=Data)
summary(fit)
fit<-lm(Log_Price~Basement_Area,data=Data)
summary(fit)
fit<-lm(Log_Price~Total_Bathroom,data=Data)
summary(fit)
fit<-lm(Log_Price~Overall_Qual,data=Data)
summary(fit)
fit<-lm(Log_Price~Lot_Area,data=Data)
summary(fit)
fit<-lm(Log_Price~Age_Sold,data=Data)
summary(fit)
fit<-lm(Log_Price~Year.sold,data=Data)
summary(fit)
fit<-lm(Log_Price~Central.Air.numbered+Bedroom_AbvGr+Fireplaces+Lot_Area+Gr_Liv_Area+Garage_Area+Basement_Area+Total_Bathroom+Overall_Qual+Year.sold+Age_Sold,data=Data)
summary(fit)
fit<-lm(Log_Price~Central.Air.numbered+Fireplaces+Lot_Area+Gr_Liv_Area+Garage_Area+Basement_Area+Total_Bathroom+Overall_Qual+Year.sold+Age_Sold,data=Data)
summary(fit)